# Generated by Django 2.2.25 on 2022-01-17 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myrecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredients', models.CharField(max_length=32)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='therecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=32)),
                ('gongyi', models.CharField(max_length=32)),
                ('flavor', models.CharField(max_length=32)),
                ('zuofa', models.TextField()),
                ('Ingre', models.TextField(default=None)),
            ],
            options={
                'db_table': 'therecipes',
            },
        ),
    ]
