# Generated by Django 2.2.25 on 2022-01-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='filterrecipe2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=32)),
                ('gongyi', models.CharField(max_length=32)),
                ('flavor', models.CharField(max_length=32)),
                ('zuofa', models.TextField()),
                ('Ingre', models.TextField(default=None)),
            ],
            options={
                'db_table': 'filterrecipes2',
            },
        ),
    ]
