# Generated by Django 2.2.25 on 2022-02-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_coments_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='pinglun',
        ),
    ]
