# Generated by Django 2.2.25 on 2022-02-13 21:12

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220213_0410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pinglun',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='coments',
            name='To',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, related_name='comen', to='myapp.therecipes'),
        ),
    ]
