# Generated by Django 2.2.25 on 2022-02-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220213_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coments',
        ),
    ]
